### ISSUE TITLE
while installing at production level we face issue reported below

### ISSUE THREAD

**Issue by zebap** [smartnav/fcm-notification#9]
when in try to install and run the command as
 npm install fcm-notification --save

below issue reported 

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: Object https://node-precompiled-binaries.grpc.io/grpc/v1.24.2/node-v11-linux-x64-glibc.tar.gz has no method 'startsWith'
node-pre-gyp ERR! stack     at /usr/id-multiple-city-core-api/node_modules/fcm-notification/node_modules/firebase-admin/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/install.js:263:45
node-pre-gyp ERR! stack     at /usr/id-multiple-city-core-api/node_modules/fcm-notification/node_modules/firebase-admin/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/grpc/node_modules/mkdirp/index.js:30:20
node-pre-gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
node-pre-gyp ERR! System Linux 3.10.0-327.36.1.el7.x86_64
node-pre-gyp ERR! command "node" "/usr/id-multiple-city-core-api/node_modules/fcm-notification/node_modules/firebase-admin/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /usr/id-multiple-city-core-api/node_modules/fcm-notification/node_modules/firebase-admin/node_modules/@google-cloud/firestore/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v0.10.46
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! Linux 3.10.0-327.36.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "fcm-notification" "--save"
npm ERR! node v0.10.46
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! grpc@1.24.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the grpc@1.24.2 install script 'node-pre-gyp install --fallback-to-build --library=static_library'.
npm ERR! This is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/id-multiple-city-core-api/npm-debug.log
any solution??? thanks in advance

**Comment by sagarss1911** [comment]
me too
